# Generated by Django 3.1.1 on 2020-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=15)),
                ('rating', models.CharField(max_length=15)),
                ('release_date', models.CharField(max_length=15)),
            ],
        ),
    ]
